server:
  port: 8180
images:
  entries:
    - alias: cwd
      path: .
      order: NAME # PATH, NAME, UPDATE
      direction: DESC # ASC, DESC
    - alias: root
      path: /
      order: NAME # PATH, NAME, UPDATE
      direction: DESC # ASC, DESC
