server:
  port: 1080
images:
  entries:
    - alias: byNameASC
      path: .
      order: NAME # PATH, NAME, UPDATE, SIZE
      direction: ASC # ASC, DESC
    - alias: byNameDESC
      path: .
      order: NAME
      direction: DESC
    - alias: byPathASC
      path: .
      order: PATH
      direction: ASC
    - alias: byPathDESC
      path: .
      order: PATH
      direction: DESC
    - alias: byUpdateASC
      path: .
      order: UPDATE
      direction: ASC
    - alias: byUpdateDESC
      path: .
      order: UPDATE
      direction: DESC
    - alias: bySizeASC
      path: .
      order: SIZE
      direction: ASC
    - alias: bySizeDESC
      path: .
      order: SIZE
      direction: DESC
    - alias: rootByNameASC
      path: /
      order: NAME # PATH, NAME, UPDATE, SIZE
      direction: ASC # ASC, DESC
    - alias: rootByNameDESC
      path: /
      order: NAME
      direction: DESC
    - alias: rootByPathASC
      path: /
      order: PATH
      direction: ASC
    - alias: rootByPathDESC
      path: /
      order: PATH
      direction: DESC
    - alias: rootByUpdateASC
      path: /
      order: UPDATE
      direction: ASC
    - alias: rootByUpdateDESC
      path: /
      order: UPDATE
      direction: DESC
    - alias: rootBySizeASC
      path: /
      order: SIZE
      direction: ASC
    - alias: rootBySizeDESC
      path: /
      order: SIZE
      direction: DESC
